/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Julio Cesar (https://sketchfab.com/juliocesarguedes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hostel-5f106e3f944442bfa7d1f028d4cc5880
Title: Hostel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Hostel = (props) => {
  const { nodes, materials } = useGLTF('/models/hostel.glb')  

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.313, 0]} scale={[18.014, 0.427, 18.014]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1_lambert3_0.geometry}
          material={materials.lambert3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1_lambert4_0.geometry}
          material={materials.lambert4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </group>
      <group position={[1.554, 9.931, 1.776]} scale={[1.562, 2.684, 1.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[-1.407, 9.931, 1.776]} scale={[1.562, 2.684, 1.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube4_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube4_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[-1.407, 6.48, 1.776]} scale={[1.562, 2.684, 1.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube5_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[1.554, 6.48, 1.776]} scale={[1.562, 2.684, 1.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube6_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube6_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[0, 3.596, 2.911]} scale={[4.913, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube9_lambert12_0.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube9_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube9_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[-1.407, 1.617, 1.776]} scale={[1.562, 3.508, 1.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube10_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube10_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[0.154, 2.011, 1.776]} scale={[1.562, 2.713, 1.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube11_lambert7_0.geometry}
          material={materials.lambert7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube11_lambert10_0.geometry}
          material={materials.lambert10}
        />
      </group>
      <group position={[-2.094, -0.296, -2.367]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface3_lambert12_0.geometry}
          material={materials.lambert12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface4_lambert12_0.geometry}
          material={materials.lambert12}
          position={[2.418, 1.473, 0]}
        />
      </group>
      <group position={[-2.246, 0.118, -0.036]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface2_lambert12_0.geometry}
          material={materials.lambert12}
          position={[0.487, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube2_lambert11_0.geometry}
        material={materials.lambert11}
        position={[0, 6.957, 0]}
        scale={[5.063, 12.86, 4.822]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube12_lambert9_0.geometry}
        material={materials.lambert9}
        position={[3.438, 8.237, 1.952]}
        scale={[1, 5.727, 0.24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube13_lambert8_0.geometry}
        material={materials.lambert8}
        position={[3.032, 5.814, 1.95]}
        scale={[1, 0.322, 0.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube14_lambert8_0.geometry}
        material={materials.lambert8}
        position={[3.032, 6.937, 1.95]}
        scale={[1, 0.322, 0.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube15_lambert8_0.geometry}
        material={materials.lambert8}
        position={[3.032, 8.072, 1.95]}
        scale={[1, 0.322, 0.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube16_lambert8_0.geometry}
        material={materials.lambert8}
        position={[3.032, 9.189, 1.95]}
        scale={[1, 0.322, 0.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube17_lambert8_0.geometry}
        material={materials.lambert8}
        position={[3.032, 10.366, 1.95]}
        scale={[1, 0.322, 0.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube20_lambert12_0.geometry}
        material={materials.lambert12}
        position={[0.145, -2.51, -2.367]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube21_lambert12_0.geometry}
        material={materials.lambert12}
        position={[-0.423, 3.186, -2.367]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube23_lambert12_0.geometry}
        material={materials.lambert12}
        position={[-2.246, -4.358, -0.139]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube24_lambert12_0.geometry}
        material={materials.lambert12}
        position={[-2.246, 3.257, -1.349]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube26_lambert5_0.geometry}
        material={materials.lambert5}
        position={[-6.142, 1.32, 1.277]}
        scale={[0.439, 1.586, 0.439]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube27_lambert6_0.geometry}
        material={materials.lambert6}
        position={[-6.142, 4.129, 1.277]}
        scale={[1.323, 4.958, 1.323]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube28_lambert6_0.geometry}
        material={materials.lambert6}
        position={[6.681, 3.713, -1.318]}
        scale={[1.087, 4.127, 1.087]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube29_lambert5_0.geometry}
        material={materials.lambert5}
        position={[6.681, 1.32, -1.318]}
        scale={[0.439, 1.586, 0.439]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube30_lambert6_0.geometry}
        material={materials.lambert6}
        position={[5.971, 3.062, 2.358]}
        scale={[1.078, 2.824, 1.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube31_lambert5_0.geometry}
        material={materials.lambert5}
        position={[5.971, 1.32, 2.358]}
        scale={[0.439, 1.586, 0.439]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube34_lambert8_0.geometry}
        material={materials.lambert8}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube35_lambert8_0.geometry}
        material={materials.lambert8}
        position={[12.145, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.typeMesh1_typeBlinn_0.geometry}
        material={materials.typeBlinn}
        position={[3.14, 10.251, 2.012]}
        scale={[0.097, 0.097, 0.048]}
      />
    </group>
  )
}

useGLTF.preload('/models/hostel.glb') // Corrected path here

export default Hostel;
